#!/bin/bash

TUNED="/etc/postgresql/10/main/postgresql.conf.tuned"
CONF="/etc/postgresql/10/main/postgresql.conf"
SAMPLE="/etc/postgresql/10/main/postgresql.conf.sample"
PGDB="ongres"
FULLLOG="bench.log"
SECS=${1:-300}


function pause(){ 
  sleep 1
}

function test(){
  for conns in 100 200 300 500 700
  do
    pgbench -n -r --time=${SECS} -c ${conns} ${PGDB} >> ${FULLLOG}_${TEST} 
    pause
    fuckcache
  done
}

function setdef(){
  cp $SAMPLE $CONF
  TEST="DEFAULT"
}

function settuned(){
  cp $TUNED $CONF
  TEST="TUNED"
}

function fuckcache(){
  sudo bash -c "sync && echo 3 > /proc/sys/vm/drop_caches"
}

function vacan(){
  vacuumdb -z $PGDB
}

function rest(){
  sudo service postgresql restart
  pause
}

setdef
rest
vacan
test
pause
settuned
rest
vacan
test

exit 0

