#!/bin/bash
FILE=$1

header="conn,latency,tps_inc,tps_exc,duration_secs,count_proc"

printf "${header}"

while read lin
do
  if [[ $lin =~ client ]] 
  then
    conns=$(echo ${lin} | cut -d ' ' -f 4) 
    printf "\n${conns}," 
  elif [[ $lin =~ latency ]] 
  then
    lat=$(echo $lin | cut -d ' ' -f4)
    printf "$lat," 
  elif [[ $lin =~ including ]]
  then
    inc=$(echo $lin | cut -d ' ' -f3)
    printf "$inc,"
  elif [[ $lin =~ excluding ]]
  then
    exc=$(echo $lin | cut -d ' ' -f3)
    printf "$exc,"
  elif [[ $lin =~ duration ]]
  then
    dura=$(echo $lin | cut -d ' ' -f2)
    printf "$dura,"
  elif [[ $lin =~ processed ]]
  then
    proc=$(echo $lin | cut -d ' ' -f6)
    printf "${proc}"
  fi
done < $FILE

printf "\n"
