#!/bin/bash
FILE=$1

header="conn,duration_secs,count_proc,latency,tps_inc,tps_exc"

printf "${header}"

while read lin
do
  if [[ $lin =~ client ]] 
  then
    conns=$(echo ${lin} | cut -d ' ' -f 4) 
    printf "\n${conns}," 
  fi

  if [[ $lin =~ duration ]]
  then
    dura=$(echo $lin | cut -d ' ' -f2)
    printf "$dura,"
  fi

  if [[ $lin =~ processed ]]
  then
    proc=$(echo $lin | cut -d ' ' -f6)
    printf "$proc,"
  fi

  if [[ $lin =~ latency ]] 
  then
    lat=$(echo $lin | cut -d ' ' -f4)
    printf "$lat," 
  fi

  if [[ $lin =~ including ]]
  then
    inc=$(echo $lin | cut -d ' ' -f3)
    printf "$inc,"
  fi

  if [[ $lin =~ excluding ]]
  then
    exc=$(echo $lin | cut -d ' ' -f3)
    printf "$exc"
  fi

done < $FILE

printf "\n"
